/*
 * Copyright COCKTAIL (www.cocktail.org), 1995, 2011 This software
 * is governed by the CeCILL license under French law and abiding by the
 * rules of distribution of free software. You can use, modify and/or
 * redistribute the software under the terms of the CeCILL license as
 * circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability. In this
 * respect, the user's attention is drawn to the risks associated with loading,
 * using, modifying and/or developing or reproducing the software by the user
 * in light of its specific status of free software, that may mean that it
 * is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security. The
 * fact that you are presently reading this means that you have had knowledge
 * of the CeCILL license and that you accept its terms.
 */
package edtscol.client.gestioncontraintes;

public class GestionContraintesIndisponibilitesView extends javax.swing.JPanel {

	public GestionContraintesIndisponibilitesView() {
		super();
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
	 * method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		panelDisponibilites = new javax.swing.JPanel();
		panelSemaines = new javax.swing.JPanel();
		panelJours = new javax.swing.JPanel();

		panelDisponibilites.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Indisponibilités",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma",
						1, 12))); // NOI18N

		panelSemaines.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Semaines...",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma",
						1, 11))); // NOI18N

		org.jdesktop.layout.GroupLayout panelSemainesLayout = new org.jdesktop.layout.GroupLayout(panelSemaines);
		panelSemaines.setLayout(panelSemainesLayout);
		panelSemainesLayout.setHorizontalGroup(panelSemainesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 835,
				Short.MAX_VALUE));
		panelSemainesLayout.setVerticalGroup(panelSemainesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 141,
				Short.MAX_VALUE));

		panelJours.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jours...", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

		org.jdesktop.layout.GroupLayout panelJoursLayout = new org.jdesktop.layout.GroupLayout(panelJours);
		panelJours.setLayout(panelJoursLayout);
		panelJoursLayout.setHorizontalGroup(panelJoursLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(0, 835, Short.MAX_VALUE));
		panelJoursLayout.setVerticalGroup(panelJoursLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(0, 226, Short.MAX_VALUE));

		org.jdesktop.layout.GroupLayout panelDisponibilitesLayout = new org.jdesktop.layout.GroupLayout(panelDisponibilites);
		panelDisponibilites.setLayout(panelDisponibilitesLayout);
		panelDisponibilitesLayout.setHorizontalGroup(panelDisponibilitesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				panelDisponibilitesLayout
						.createSequentialGroup()
						.addContainerGap()
						.add(panelDisponibilitesLayout
								.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(org.jdesktop.layout.GroupLayout.TRAILING, panelJours, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.add(org.jdesktop.layout.GroupLayout.TRAILING, panelSemaines, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)).addContainerGap()));
		panelDisponibilitesLayout.setVerticalGroup(panelDisponibilitesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(org.jdesktop.layout.GroupLayout.TRAILING,
						panelDisponibilitesLayout
								.createSequentialGroup()
								.add(panelSemaines, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
								.add(panelJours, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				org.jdesktop.layout.GroupLayout.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap()
						.add(panelDisponibilites, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup()
						.addContainerGap()
						.add(panelDisponibilites, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addContainerGap()));
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	protected javax.swing.ButtonGroup buttonGroup1;
	protected javax.swing.JPanel panelDisponibilites;
	protected javax.swing.JPanel panelJours;
	protected javax.swing.JPanel panelSemaines;

	// End of variables declaration//GEN-END:variables

	public javax.swing.JPanel getPanelSemaines() {
		return panelSemaines;
	}

	public javax.swing.JPanel getPanelJours() {
		return panelJours;
	}

}
