
SET DEFINE OFF;

-- 
-- __________________________________________________________
--  /!\ ATTENTION /!\ fichier encodé en UTF-8 sans BOM
-- (il peut contenir des é è ç à î ê ô ...)
-- __________________________________________________________
--
--

--
-- Fichier : 1
-- Type : DDL
-- Schéma : EDTSCOL
-- Numéro de version : 1.4.0.0
-- Pré-requis : base version 1.3.9.3 ou 1.3.9.4
-- Date de publication : 27/10/2011
-- Auteur(s) : Patrice DE MEYER
-- Licence : CeCILL version 2
--
-- A lancer sous : GRHUM
--
--

ALTER TABLE EDTSCOL.RESERVATION_OBJET ADD (MOTIF_ANNULATION VARCHAR2(500 BYTE));

COMMENT ON COLUMN EDTSCOL.RESERVATION_OBJET.MOTIF_ANNULATION IS 'Motif d''annulation spécifique pour l''application Kiosque';

--

ALTER TABLE EDTSCOL.PREF_USER ADD AFF_HORAIRES_HAMAC NUMBER;

COMMENT ON COLUMN EDTSCOL.PREF_USER.AFF_HORAIRES_HAMAC IS '(0/1) Est-ce qu''on affiche les horaires de travail déclarés dans Hamac sur le planning individu ?';

--

ALTER TABLE EDTSCOL.PREF_USER ADD INTERVALLE_MINIMUM NUMBER;

COMMENT ON COLUMN EDTSCOL.PREF_USER.INTERVALLE_MINIMUM IS 'Intervalle minimum en minutes à laisser entre les réservations lors de placement automatique (mode expert ou réservation auto)';

--

CREATE TABLE EDTSCOL.MESSAGES (
  MSG_LIB VARCHAR2(500) NOT NULL,
  MSG_REPEAT VARCHAR2(1) NOT NULL,
  CONSTRAINT MESSAGES_PK PRIMARY KEY (
    MSG_LIB
  )    
);


COMMENT ON COLUMN EDTSCOL.MESSAGES.MSG_LIB IS 'Message à afficher aux clients';

COMMENT ON COLUMN EDTSCOL.MESSAGES.MSG_REPEAT IS '''O'' ou ''N'' : si ''O'', répète régulièrement le message aux clients (avec possibilité pour chaque client de désactiver la répétition) ; si ''N'', ne l''affiche qu''une fois';
ALTER TABLE EDTSCOL.MESSAGES
 ADD CONSTRAINT MSG_REPEAT_CHK
 CHECK (MSG_REPEAT IN ('O', 'N'));

--

ALTER TABLE EDTSCOL.PREF_SCOL ADD MRSEM_KEY NUMBER;

COMMENT ON COLUMN EDTSCOL.PREF_SCOL.MRSEM_KEY IS 'Semestre / parcours précis, facultatif';

--

create or replace view edtscol.v_maquette_ap_groupes (mapg_key, map_key, map_libelle, map_libelle_affichage, map_valeur, map_seuil, map_groupe_prevu,
  gobj_key, ggrp_key, ggrp_code, ggrp_libelle) 
as
  select map.map_key || '-', map.map_key, map.map_libelle, map.map_libelle, map.map_valeur, map.map_seuil, map.map_groupe_prevu,
    null, null, null, null
  from scolarite.scol_maquette_ap map
union
  select map.map_key || '-' || gobj.gobj_key, map.map_key, map.map_libelle, '            '  || map.map_libelle, map.map_valeur, map.map_seuil,
    1, gobj.gobj_key, ggrp.ggrp_key, ggrp.ggrp_code, ggrp.ggrp_libelle
  from scolarite.scol_maquette_ap map, scolarite.scol_groupe_objet gobj, scolarite.scol_groupe_grp ggrp
  where map.map_key = gobj.map_key
  and map.fann_key = gobj.fann_key
  and gobj.ggrp_key = ggrp.ggrp_key;

--

create or replace view edtscol.v_scol_maquette_ap_ec (map_key, mec_key)
as
select mrap.map_key, mrap.mec_key
from scolarite.scol_maquette_repartition_ap mrap
where mrap_majeur = 'O' or mrap_majeur is null;

--

CREATE TABLE EDTSCOL.CTRL_INDIVIDU_SEMAINES (
  CIS_KEY INTEGER NOT NULL,
  NO_INDIVIDU INTEGER NOT NULL,
  FANN_KEY INTEGER NOT NULL,
  CIS_DATE DATE NOT NULL,
  CIS_NO_SEMAINE INTEGER NOT NULL,
  CONSTRAINT CTRL_INDIVIDU_SEMAINES_PK PRIMARY KEY (
    CIS_KEY
  )    
);

ALTER TABLE EDTSCOL.CTRL_INDIVIDU_SEMAINES ADD (
  CONSTRAINT FK_CTRL_IND_SEM_NO_INDIV 
 FOREIGN KEY (NO_INDIVIDU) 
 REFERENCES GRHUM.INDIVIDU_ULR (NO_INDIVIDU));

GRANT REFERENCES ON SCOLARITE.SCOL_FORMATION_ANNEE TO EDTSCOL;

ALTER TABLE EDTSCOL.CTRL_INDIVIDU_SEMAINES ADD (
  CONSTRAINT FK_CTRL_IND_SEM_FANN_KEY 
 FOREIGN KEY (FANN_KEY) 
 REFERENCES SCOLARITE.SCOL_FORMATION_ANNEE (FANN_KEY));

create sequence EDTSCOL.CTRL_INDIVIDU_SEMAINES_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 NOCACHE;

--

CREATE TABLE EDTSCOL.CTRL_INDIVIDU_JOURS (
  CIJ_KEY INTEGER NOT NULL,
  CIS_KEY INTEGER NOT NULL,
  CIJ_DATE DATE NOT NULL,
  CIJ_NO_JOUR INTEGER NOT NULL,
  CONSTRAINT CTRL_INDIVIDU_JOURS_PK PRIMARY KEY (
    CIJ_KEY
  )    
);

ALTER TABLE EDTSCOL.CTRL_INDIVIDU_JOURS ADD (
  CONSTRAINT FK_CTRL_IND_JOU_CIS_KEY 
 FOREIGN KEY (CIS_KEY) 
 REFERENCES EDTSCOL.CTRL_INDIVIDU_SEMAINES (CIS_KEY));

create sequence EDTSCOL.CTRL_INDIVIDU_JOURS_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 NOCACHE;

--

CREATE TABLE EDTSCOL.CTRL_INDIVIDU_HEURES (
  CIH_KEY INTEGER NOT NULL,
  CIJ_KEY INTEGER NOT NULL,
  CIH_HEURE_DEBUT DATE NOT NULL,
  CIH_HEURE_FIN DATE NOT NULL,
  CONSTRAINT CTRL_INDIVIDU_HEURES_PK PRIMARY KEY (
    CIH_KEY
  )    
);

ALTER TABLE EDTSCOL.CTRL_INDIVIDU_HEURES ADD (
  CONSTRAINT FK_CTRL_IND_HEU_CIJ_KEY 
 FOREIGN KEY (CIJ_KEY) 
 REFERENCES EDTSCOL.CTRL_INDIVIDU_JOURS (CIJ_KEY));

create sequence EDTSCOL.CTRL_INDIVIDU_HEURES_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 NOCACHE;

--

CREATE TABLE EDTSCOL.CTRL_PARAM_HABILITATION (
  CPH_KEY INTEGER NOT NULL,
  FHAB_KEY INTEGER NOT NULL,
  CPH_LUN_HEURE_DEB INTEGER,
  CPH_LUN_HEURE_FIN INTEGER,
  CPH_MAR_HEURE_DEB INTEGER,
  CPH_MAR_HEURE_FIN INTEGER,
  CPH_MER_HEURE_DEB INTEGER,
  CPH_MER_HEURE_FIN INTEGER,
  CPH_JEU_HEURE_DEB INTEGER,
  CPH_JEU_HEURE_FIN INTEGER,
  CPH_VEN_HEURE_DEB INTEGER,
  CPH_VEN_HEURE_FIN INTEGER,
  CPH_SAM_HEURE_DEB INTEGER,
  CPH_SAM_HEURE_FIN INTEGER,
  CPH_DIM_HEURE_DEB INTEGER,
  CPH_DIM_HEURE_FIN INTEGER,
  CONSTRAINT CTRL_PARAM_HABILITATION_PK PRIMARY KEY (
    CPH_KEY
  )    
);

GRANT REFERENCES ON SCOLARITE.SCOL_FORMATION_HABILITATION TO EDTSCOL;

ALTER TABLE EDTSCOL.CTRL_PARAM_HABILITATION ADD (
  CONSTRAINT FK_CTRL_PARAM_HABI_FHAB_KEY 
 FOREIGN KEY (FHAB_KEY) 
 REFERENCES SCOLARITE.SCOL_FORMATION_HABILITATION (FHAB_KEY));

create sequence EDTSCOL.CTRL_PARAM_HABILITATION_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 NOCACHE;

--

CREATE TABLE EDTSCOL.CTRL_PARAM_AP (
  CPA_KEY INTEGER NOT NULL,
  MAP_KEY INTEGER NOT NULL,
  GGRP_KEY INTEGER,
  CPA_DUREE INTEGER,
  CPA_LUN_HEURE_DEB INTEGER,
  CPA_LUN_HEURE_FIN INTEGER,
  CPA_MAR_HEURE_DEB INTEGER,
  CPA_MAR_HEURE_FIN INTEGER,
  CPA_MER_HEURE_DEB INTEGER,
  CPA_MER_HEURE_FIN INTEGER,
  CPA_JEU_HEURE_DEB INTEGER,
  CPA_JEU_HEURE_FIN INTEGER,
  CPA_VEN_HEURE_DEB INTEGER,
  CPA_VEN_HEURE_FIN INTEGER,
  CPA_SAM_HEURE_DEB INTEGER,
  CPA_SAM_HEURE_FIN INTEGER,
  CPA_DIM_HEURE_DEB INTEGER,
  CPA_DIM_HEURE_FIN INTEGER,
  CONSTRAINT CTRL_PARAM_AP_PK PRIMARY KEY (
    CPA_KEY
  )    
);

ALTER TABLE EDTSCOL.CTRL_PARAM_AP ADD (
  CONSTRAINT FK_CTRL_PARAM_AP_MAP_KEY 
 FOREIGN KEY (MAP_KEY) 
 REFERENCES SCOLARITE.SCOL_MAQUETTE_AP (MAP_KEY));

GRANT REFERENCES ON SCOLARITE.SCOL_GROUPE_GRP TO EDTSCOL;

ALTER TABLE EDTSCOL.CTRL_PARAM_AP ADD (
  CONSTRAINT FK_CTRL_PARAM_AP_GGRP_KEY 
 FOREIGN KEY (GGRP_KEY) 
 REFERENCES SCOLARITE.SCOL_GROUPE_GRP (GGRP_KEY));

create sequence EDTSCOL.CTRL_PARAM_AP_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 NOCACHE;

--

CREATE TABLE EDTSCOL.CTRL_PARAM_AP_INDIVIDU (
  CPAI_KEY INTEGER NOT NULL,
  CPA_KEY INTEGER NOT NULL,
  NO_INDIVIDU INTEGER NOT NULL,
  CONSTRAINT CTRL_PARAM_AP_INDIVIDU_PK PRIMARY KEY (
    CPAI_KEY
  )    
);

ALTER TABLE EDTSCOL.CTRL_PARAM_AP_INDIVIDU ADD (
  CONSTRAINT FK_CTRL_PARAM_AP_IND_CPA_KEY 
 FOREIGN KEY (CPA_KEY) 
 REFERENCES EDTSCOL.CTRL_PARAM_AP (CPA_KEY));

ALTER TABLE EDTSCOL.CTRL_PARAM_AP_INDIVIDU ADD (
  CONSTRAINT FK_CTRL_PARAM_AP_IND_NO_IND 
 FOREIGN KEY (NO_INDIVIDU) 
 REFERENCES GRHUM.INDIVIDU_ULR (NO_INDIVIDU));

create sequence EDTSCOL.CTRL_PARAM_AP_INDIVIDU_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 NOCACHE;

--

CREATE TABLE EDTSCOL.CTRL_PARAM_AP_SALLE (
  CPAS_KEY INTEGER NOT NULL,
  CPA_KEY INTEGER NOT NULL,
  SAL_NUMERO INTEGER NOT NULL,
  CONSTRAINT CTRL_PARAM_AP_SALLE_PK PRIMARY KEY (
    CPAS_KEY
  )    
);

ALTER TABLE EDTSCOL.CTRL_PARAM_AP_SALLE ADD (
  CONSTRAINT FK_CTRL_PARAM_AP_SAL_CPA_KEY 
 FOREIGN KEY (CPA_KEY) 
 REFERENCES EDTSCOL.CTRL_PARAM_AP (CPA_KEY));

ALTER TABLE EDTSCOL.CTRL_PARAM_AP_SALLE ADD (
  CONSTRAINT FK_CTRL_PARAM_AP_SAL_SAL_NUM 
 FOREIGN KEY (SAL_NUMERO) 
 REFERENCES GRHUM.SALLES (SAL_NUMERO));

create sequence EDTSCOL.CTRL_PARAM_AP_SALLE_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 NOCACHE;

--

CREATE TABLE EDTSCOL.CTRL_PARAM_AP_SALLE_CHOIX (
  CPASC_KEY INTEGER NOT NULL,
  CPA_KEY INTEGER NOT NULL,
  SAL_NUMERO INTEGER NOT NULL,
  CONSTRAINT CTRL_PARAM_AP_SALLEC_PK PRIMARY KEY (
    CPASC_KEY
  )    
);

ALTER TABLE EDTSCOL.CTRL_PARAM_AP_SALLE_CHOIX ADD (
  CONSTRAINT FK_CTRL_PARAM_AP_SALC_CPA_KEY 
 FOREIGN KEY (CPA_KEY) 
 REFERENCES EDTSCOL.CTRL_PARAM_AP (CPA_KEY));

ALTER TABLE EDTSCOL.CTRL_PARAM_AP_SALLE_CHOIX ADD (
  CONSTRAINT FK_CTRL_PARAM_AP_SALC_SAL_NUM 
 FOREIGN KEY (SAL_NUMERO) 
 REFERENCES GRHUM.SALLES (SAL_NUMERO));

create sequence EDTSCOL.CTRL_PARAM_AP_SALLE_CHOIX_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 NOCACHE;

--

CREATE TABLE EDTSCOL.CTRL_PARAM_AP_OBJET (
  CPAO_KEY INTEGER NOT NULL,
  CPA_KEY INTEGER NOT NULL,
  RO_KEY INTEGER NOT NULL,
  CONSTRAINT CTRL_PARAM_AP_OBJET_PK PRIMARY KEY (
    CPAO_KEY
  )    
);

ALTER TABLE EDTSCOL.CTRL_PARAM_AP_OBJET ADD (
  CONSTRAINT FK_CTRL_PARAM_AP_OBJ_CPA_KEY 
 FOREIGN KEY (CPA_KEY) 
 REFERENCES EDTSCOL.CTRL_PARAM_AP (CPA_KEY));

ALTER TABLE EDTSCOL.CTRL_PARAM_AP_OBJET ADD (
  CONSTRAINT FK_CTRL_PARAM_AP_OBJ_RO_KEY 
 FOREIGN KEY (RO_KEY) 
 REFERENCES EDTSCOL.RESA_OBJET (RO_KEY));

create sequence EDTSCOL.CTRL_PARAM_AP_OBJET_SEQ INCREMENT BY 1 START WITH 1 MINVALUE 1 NOCACHE;

--

COMMIT;
