
SET DEFINE OFF;

-- 
-- __________________________________________________________
--  /!\ ATTENTION /!\ fichier encodé en UTF-8 sans BOM
-- (il peut contenir des é è ç à î ê ô ...)
-- __________________________________________________________
--
--

--
-- Fichier : 1
-- Type : DDL
-- Schéma : EDTSCOL
-- Numéro de version : 1.4.0.2
-- Pré-requis : base version 1.4.0.0 ou 1.4.0.1
-- Date de publication : 20/12/2011
-- Auteur(s) : Patrice DE MEYER
-- Licence : CeCILL version 2
--
-- A lancer sous : EDTSCOL
--

--

grant delete on edtscol.ctrl_param_ap to scolarite;
grant delete on edtscol.ctrl_param_ap_individu to scolarite;
grant delete on edtscol.ctrl_param_ap_objet to scolarite;
grant delete on edtscol.ctrl_param_ap_salle to scolarite;
grant delete on edtscol.ctrl_param_ap_salle_choix to scolarite;

--

ALTER TABLE EDTSCOL.CTRL_PARAM_AP DROP CONSTRAINT FK_CTRL_PARAM_AP_GGRP_KEY;
ALTER TABLE EDTSCOL.CTRL_PARAM_AP_INDIVIDU DROP CONSTRAINT FK_CTRL_PARAM_AP_IND_CPA_KEY;
ALTER TABLE EDTSCOL.CTRL_PARAM_AP_OBJET DROP CONSTRAINT FK_CTRL_PARAM_AP_OBJ_CPA_KEY;
ALTER TABLE EDTSCOL.CTRL_PARAM_AP_SALLE DROP CONSTRAINT FK_CTRL_PARAM_AP_SAL_CPA_KEY;
ALTER TABLE EDTSCOL.CTRL_PARAM_AP_SALLE_CHOIX DROP CONSTRAINT FK_CTRL_PARAM_AP_SALC_CPA_KEY;
ALTER TABLE SCOLARITE.SCOL_GROUPE_GRP DROP CONSTRAINT GGRP_REF_GCOL;

ALTER TABLE EDTSCOL.CTRL_PARAM_AP ADD (
  CONSTRAINT FK_CTRL_PARAM_AP_GGRP_KEY 
 FOREIGN KEY (GGRP_KEY) 
 REFERENCES SCOLARITE.SCOL_GROUPE_GRP (GGRP_KEY)
 DEFERRABLE INITIALLY DEFERRED);

ALTER TABLE EDTSCOL.CTRL_PARAM_AP_INDIVIDU ADD (
  CONSTRAINT FK_CTRL_PARAM_AP_IND_CPA_KEY 
 FOREIGN KEY (CPA_KEY) 
 REFERENCES EDTSCOL.CTRL_PARAM_AP (CPA_KEY)
 DEFERRABLE INITIALLY DEFERRED);

ALTER TABLE EDTSCOL.CTRL_PARAM_AP_OBJET ADD (
  CONSTRAINT FK_CTRL_PARAM_AP_OBJ_CPA_KEY 
 FOREIGN KEY (CPA_KEY) 
 REFERENCES EDTSCOL.CTRL_PARAM_AP (CPA_KEY)
 DEFERRABLE INITIALLY DEFERRED);

ALTER TABLE EDTSCOL.CTRL_PARAM_AP_SALLE ADD (
  CONSTRAINT FK_CTRL_PARAM_AP_SAL_CPA_KEY 
 FOREIGN KEY (CPA_KEY) 
 REFERENCES EDTSCOL.CTRL_PARAM_AP (CPA_KEY)
 DEFERRABLE INITIALLY DEFERRED);

ALTER TABLE EDTSCOL.CTRL_PARAM_AP_SALLE_CHOIX ADD (
  CONSTRAINT FK_CTRL_PARAM_AP_SALC_CPA_KEY 
 FOREIGN KEY (CPA_KEY) 
 REFERENCES EDTSCOL.CTRL_PARAM_AP (CPA_KEY)
 DEFERRABLE INITIALLY DEFERRED);

ALTER TABLE SCOLARITE.SCOL_GROUPE_GRP ADD (
  CONSTRAINT GGRP_REF_GCOL 
 FOREIGN KEY (GCOL_KEY) 
 REFERENCES SCOLARITE.SCOL_GROUPE_COLLECTION (GCOL_KEY)
 DEFERRABLE INITIALLY DEFERRED);

--

CREATE TABLE EDTSCOL.CONTRAINTE_SEMAINE (
  CTS_KEY INTEGER NOT NULL,
  FANN_KEY INTEGER NOT NULL,
  CTS_DATE DATE NOT NULL,
  CTS_NO_SEMAINE INTEGER NOT NULL,
  NO_INDIVIDU INTEGER,
  CONSTRAINT CTS_PK PRIMARY KEY (
    CTS_KEY
  )    
);

ALTER TABLE EDTSCOL.CONTRAINTE_SEMAINE ADD (
  CONSTRAINT FK_CTS_FANN_KEY 
 FOREIGN KEY (FANN_KEY) 
 REFERENCES SCOLARITE.SCOL_FORMATION_ANNEE (FANN_KEY));

ALTER TABLE EDTSCOL.CONTRAINTE_SEMAINE ADD (
  CONSTRAINT FK_CTS_NO_INDIV 
 FOREIGN KEY (NO_INDIVIDU) 
 REFERENCES GRHUM.INDIVIDU_ULR (NO_INDIVIDU));

--

CREATE TABLE EDTSCOL.CONTRAINTE_JOUR (
  CTJ_KEY INTEGER NOT NULL,
  CTS_KEY INTEGER NOT NULL,
  CTJ_DATE DATE NOT NULL,
  CTJ_NO_JOUR INTEGER NOT NULL,
  CONSTRAINT CTJ_PK PRIMARY KEY (
    CTJ_KEY
  )    
);

ALTER TABLE EDTSCOL.CONTRAINTE_JOUR ADD (
  CONSTRAINT FK_CTJ_CTS_KEY 
 FOREIGN KEY (CTS_KEY) 
 REFERENCES EDTSCOL.CONTRAINTE_SEMAINE (CTS_KEY)
 DEFERRABLE INITIALLY DEFERRED);

--

CREATE TABLE EDTSCOL.CONTRAINTE_HEURE (
  CTH_KEY INTEGER NOT NULL,
  CTJ_KEY INTEGER NOT NULL,
  CTH_HEURE_DEBUT DATE NOT NULL,
  CTH_HEURE_FIN DATE NOT NULL,
  CONSTRAINT CTH_PK PRIMARY KEY (
    CTH_KEY
  )    
);

ALTER TABLE EDTSCOL.CONTRAINTE_HEURE ADD (
  CONSTRAINT FK_CTH_CTJ_KEY 
 FOREIGN KEY (CTJ_KEY) 
 REFERENCES EDTSCOL.CONTRAINTE_JOUR (CTJ_KEY)
 DEFERRABLE INITIALLY DEFERRED);

--

COMMIT;
