-- !!!!!!!!!!! INDIQUER UN MOT DE PASSE (identified by ...) !!!!!!!!!!!
-- (et ne pas toucher au nom des users :-) )
-- EXECUTER DEPUIS GRHUM !!!!

--
CREATE USER edtscol
  IDENTIFIED BY edtscol
  DEFAULT TABLESPACE GRH
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON GRH;
  
GRANT CREATE SESSION TO edtscol;
GRANT CREATE TABLE TO edtscol;
GRANT CREATE SYNONYM TO edtscol;
GRANT CREATE VIEW TO edtscol;
GRANT CREATE SEQUENCE TO edtscol;
GRANT CREATE PROCEDURE TO edtscol;
GRANT CREATE TRIGGER TO edtscol;
GRANT SELECT ANY TABLE TO edtscol;
GRANT SELECT ANY SEQUENCE TO edtscol;
GRANT REFERENCES ON grhum.individu_ulr to edtscol;
GRANT REFERENCES ON grhum.salles to edtscol;
GRANT INSERT ANY TABLE to edtscol;
GRANT UPDATE ANY TABLE to edtscol;
GRANT DELETE ANY TABLE to edtscol;
GRANT UNLIMITED TABLESPACE TO edtscol;

--
CREATE USER reservation
  IDENTIFIED BY reservation
  DEFAULT TABLESPACE GRH
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON GRH;
  
GRANT CREATE SESSION TO reservation;
GRANT CREATE TABLE TO reservation;
GRANT CREATE SYNONYM TO reservation;
GRANT CREATE VIEW TO reservation;
GRANT CREATE SEQUENCE TO reservation;
GRANT CREATE PROCEDURE TO reservation;
GRANT CREATE TRIGGER TO reservation;
GRANT SELECT ANY TABLE TO reservation;
GRANT SELECT ANY SEQUENCE TO reservation;
GRANT INSERT ANY TABLE to reservation;
GRANT UPDATE ANY TABLE to reservation;
GRANT DELETE ANY TABLE to reservation;
GRANT UNLIMITED TABLESPACE TO reservation;
