/*
 * Copyright COCKTAIL (www.cocktail.org), 1995, 2011 This software
 * is governed by the CeCILL license under French law and abiding by the
 * rules of distribution of free software. You can use, modify and/or
 * redistribute the software under the terms of the CeCILL license as
 * circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability. In this
 * respect, the user's attention is drawn to the risks associated with loading,
 * using, modifying and/or developing or reproducing the software by the user
 * in light of its specific status of free software, that may mean that it
 * is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security. The
 * fact that you are presently reading this means that you have had knowledge
 * of the CeCILL license and that you accept its terms.
 */
package edtscol.client;

public class PreferencesView extends javax.swing.JDialog {

	public PreferencesView(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
	 * method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		buttonGroup2 = new javax.swing.ButtonGroup();
		buttonGroup3 = new javax.swing.ButtonGroup();
		buttonGroup4 = new javax.swing.ButtonGroup();
		buttonGroup5 = new javax.swing.ButtonGroup();
		buttonGroup6 = new javax.swing.ButtonGroup();
		buttonGroup7 = new javax.swing.ButtonGroup();
		buttonGroup8 = new javax.swing.ButtonGroup();
		buttonGroup9 = new javax.swing.ButtonGroup();
		buttonGroup10 = new javax.swing.ButtonGroup();
		buttonGroup11 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jLabel14 = new javax.swing.JLabel();
		anneeCivileNon = new javax.swing.JRadioButton();
		comEnsOui = new javax.swing.JRadioButton();
		btEnregistrer = new javax.swing.JButton();
		jLabel8 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		multSelectionGrpNon = new javax.swing.JRadioButton();
		parcoursComOui = new javax.swing.JRadioButton();
		colorECOui = new javax.swing.JRadioButton();
		anneeCivileOui = new javax.swing.JRadioButton();
		jLabel3 = new javax.swing.JLabel();
		examOui = new javax.swing.JRadioButton();
		sendMailOccupantsNon = new javax.swing.JRadioButton();
		jLabel11 = new javax.swing.JLabel();
		labelSendMailOccupants = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		respApNon = new javax.swing.JRadioButton();
		jLabel5 = new javax.swing.JLabel();
		tDebImpress = new javax.swing.JTextField();
		sendMailDepositairesOui = new javax.swing.JRadioButton();
		sendMailOccupantsOui = new javax.swing.JRadioButton();
		comEnsNon = new javax.swing.JRadioButton();
		jLabel4 = new javax.swing.JLabel();
		tooltipPlanningNon = new javax.swing.JRadioButton();
		respApOui = new javax.swing.JRadioButton();
		sendMailDepositairesNon = new javax.swing.JRadioButton();
		jLabel10 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		colorECNon = new javax.swing.JRadioButton();
		cbVisibilite = new javax.swing.JComboBox();
		jLabel13 = new javax.swing.JLabel();
		parcoursComNon = new javax.swing.JRadioButton();
		jLabel7 = new javax.swing.JLabel();
		multSelectionGrpOui = new javax.swing.JRadioButton();
		jLabel16 = new javax.swing.JLabel();
		tooltipPlanningOui = new javax.swing.JRadioButton();
		examNon = new javax.swing.JRadioButton();
		tFinImpress = new javax.swing.JTextField();
		jLabel17 = new javax.swing.JLabel();
		affHorairesHamacOui = new javax.swing.JRadioButton();
		affHorairesHamacNon = new javax.swing.JRadioButton();
		jLabel18 = new javax.swing.JLabel();
		tIntervalleMinimum = new javax.swing.JTextField();
		jLabel19 = new javax.swing.JLabel();
		btEnregistrer2 = new javax.swing.JButton();
		jLabel20 = new javax.swing.JLabel();
		cbTypeResa = new javax.swing.JComboBox();

		setTitle("Préférences interface de l'utilisateur");
		setResizable(false);

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel14.setText("H   à ");

		buttonGroup1.add(anneeCivileNon);
		anneeCivileNon.setSelected(true);
		anneeCivileNon.setText("Non");

		buttonGroup8.add(comEnsOui);
		comEnsOui.setText("Oui");

		btEnregistrer.setFont(new java.awt.Font("Tahoma", 0, 10));
		btEnregistrer.setText("Enregistrer");

		jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11));
		jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel8.setText("Certaines modifications ne seront prises en compte qu'au prochain lancement de l'application...");

		jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel6.setText("Utiliser des couleurs par E.C. pour afficher les réservations");

		jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel9.setText("Afficher les examens (utile uniquement en période d'examen)");

		buttonGroup4.add(multSelectionGrpNon);
		multSelectionGrpNon.setSelected(true);
		multSelectionGrpNon.setText("Non");

		buttonGroup7.add(parcoursComOui);
		parcoursComOui.setText("Oui");

		buttonGroup5.add(colorECOui);
		colorECOui.setText("Oui");

		buttonGroup1.add(anneeCivileOui);
		anneeCivileOui.setText("Oui");

		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel3.setText("Activer l'envoi de mail aux dépositaires des salles et objets");
		jLabel3.setEnabled(false);

		buttonGroup9.add(examOui);
		examOui.setText("Oui");

		buttonGroup2.add(sendMailOccupantsNon);
		sendMailOccupantsNon.setSelected(true);
		sendMailOccupantsNon.setText("Non");

		jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel11.setText("Utiliser les responsables d'EC lors de saisie d'EDT d'AP");

		labelSendMailOccupants.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		labelSendMailOccupants.setText("Activer l'envoi de mail aux occupants");

		jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel12.setText("Visibilité par défaut lors de la création   ");

		buttonGroup10.add(respApNon);
		respApNon.setText("Non");

		jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel5.setText("Utiliser une fenêtre flottante qui détaille le créneau cliqué");

		buttonGroup3.add(sendMailDepositairesOui);
		sendMailDepositairesOui.setSelected(true);
		sendMailDepositairesOui.setText("Oui");
		sendMailDepositairesOui.setEnabled(false);

		buttonGroup2.add(sendMailOccupantsOui);
		sendMailOccupantsOui.setText("Oui");

		buttonGroup8.add(comEnsNon);
		comEnsNon.setSelected(true);
		comEnsNon.setText("Non");

		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel4.setText("Activer la sélection multiple de groupes lors des réservations");

		buttonGroup6.add(tooltipPlanningNon);
		tooltipPlanningNon.setSelected(true);
		tooltipPlanningNon.setText("Non");

		buttonGroup10.add(respApOui);
		respApOui.setText("Oui");

		buttonGroup3.add(sendMailDepositairesNon);
		sendMailDepositairesNon.setText("Non");
		sendMailDepositairesNon.setEnabled(false);

		jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel10.setText("Afficher le commentaire pour une réservation d'enseignement");

		jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel15.setText("H");

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel1.setText("Année civile");

		buttonGroup5.add(colorECNon);
		colorECNon.setSelected(true);
		colorECNon.setText("Non");

		jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel13.setText("Zone d'impression (sortie PDF) : de ");

		buttonGroup7.add(parcoursComNon);
		parcoursComNon.setSelected(true);
		parcoursComNon.setText("Non");

		jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel7.setText("Fusionner l'EDT du parcours commun avec le parcours spécialisé");

		buttonGroup4.add(multSelectionGrpOui);
		multSelectionGrpOui.setText("Oui");

		jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel16.setText("d'une nouvelle réunion :");

		buttonGroup6.add(tooltipPlanningOui);
		tooltipPlanningOui.setText("Oui");

		buttonGroup9.add(examNon);
		examNon.setSelected(true);
		examNon.setText("Non");

		jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel17.setText("Afficher les horaires de travail (Hamac) sur le planning des individus");

		buttonGroup11.add(affHorairesHamacOui);
		affHorairesHamacOui.setText("Oui");

		buttonGroup11.add(affHorairesHamacNon);
		affHorairesHamacNon.setSelected(true);
		affHorairesHamacNon.setText("Non");

		jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel18.setText("Intervalle mini entre les réservations (mode expert/auto) :");

		jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel19.setText("min");

		btEnregistrer2.setFont(new java.awt.Font("Tahoma", 0, 10));
		btEnregistrer2.setText("Enregistrer");

		jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel20.setText("Type de réservation par défaut lors d'une création");

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						jPanel1Layout
								.createSequentialGroup()
								.addContainerGap()
								.add(jPanel1Layout
										.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
										.add(org.jdesktop.layout.GroupLayout.TRAILING,
												jPanel1Layout
														.createSequentialGroup()
														.add(jLabel17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 353,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(affHorairesHamacOui)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(affHorairesHamacNon))
										.add(org.jdesktop.layout.GroupLayout.TRAILING,
												jPanel1Layout
														.createSequentialGroup()
														.add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 353,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(examOui)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(examNon))
										.add(org.jdesktop.layout.GroupLayout.TRAILING,
												jPanel1Layout
														.createSequentialGroup()
														.add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 353,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(comEnsOui)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(comEnsNon))
										.add(org.jdesktop.layout.GroupLayout.TRAILING,
												jPanel1Layout
														.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
														.add(jPanel1Layout
																.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
																.add(jPanel1Layout
																		.createSequentialGroup()
																		.add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 353,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(sendMailDepositairesOui)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(sendMailDepositairesNon))
																.add(jPanel1Layout
																		.createSequentialGroup()
																		.add(labelSendMailOccupants, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				353, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(sendMailOccupantsOui)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(sendMailOccupantsNon))
																.add(jPanel1Layout
																		.createSequentialGroup()
																		.add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 353,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(anneeCivileOui)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(anneeCivileNon)))
														.add(jPanel1Layout
																.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
																.add(jPanel1Layout
																		.createSequentialGroup()
																		.add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 353,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(tooltipPlanningOui)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(tooltipPlanningNon))
																.add(jPanel1Layout
																		.createSequentialGroup()
																		.add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 353,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(colorECOui)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(colorECNon))
																.add(jPanel1Layout
																		.createSequentialGroup()
																		.add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 353,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(multSelectionGrpOui)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(multSelectionGrpNon))))
										.add(org.jdesktop.layout.GroupLayout.TRAILING,
												jPanel1Layout
														.createSequentialGroup()
														.add(jPanel1Layout
																.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
																.add(jPanel1Layout
																		.createSequentialGroup()
																		.add(jLabel13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 191,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(tDebImpress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.add(10, 10, 10)
																		.add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(tFinImpress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(jLabel15, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 27,
																				Short.MAX_VALUE))
																.add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 353,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
														.add(jPanel1Layout
																.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
																.add(jPanel1Layout.createSequentialGroup().add(parcoursComOui)
																		.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(parcoursComNon)).add(btEnregistrer)))
										.add(org.jdesktop.layout.GroupLayout.TRAILING,
												jPanel1Layout
														.createSequentialGroup()
														.add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 353,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(respApOui)
														.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(respApNon))
										.add(jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(jLabel18, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
												.add(tIntervalleMinimum, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(10, 10, 10)
												.add(jLabel19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(btEnregistrer2))
										.add(org.jdesktop.layout.GroupLayout.TRAILING,
												jPanel1Layout
														.createSequentialGroup()
														.add(jPanel1Layout
																.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
																.add(org.jdesktop.layout.GroupLayout.LEADING, jLabel12,
																		org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																		org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.add(org.jdesktop.layout.GroupLayout.LEADING, jLabel16,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 221,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(18, 18, 18)
														.add(cbVisibilite, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(jLabel20, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
												.add(18, 18, 18)
												.add(cbTypeResa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))).addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
						jPanel1Layout
								.createSequentialGroup()
								.addContainerGap()
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel1).add(anneeCivileOui)
										.add(anneeCivileNon))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(labelSendMailOccupants)
										.add(sendMailOccupantsOui).add(sendMailOccupantsNon))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel3)
										.add(sendMailDepositairesOui).add(sendMailDepositairesNon))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel4)
										.add(multSelectionGrpOui).add(multSelectionGrpNon))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel6).add(colorECOui)
										.add(colorECNon))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel5).add(tooltipPlanningOui)
										.add(tooltipPlanningNon))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(parcoursComOui)
										.add(parcoursComNon).add(jLabel7))
								.add(18, 18, 18)
								.add(jPanel1Layout
										.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel13)
										.add(jLabel14)
										.add(tDebImpress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(tFinImpress, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel15).add(btEnregistrer))
								.add(24, 24, 24)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel10).add(comEnsOui)
										.add(comEnsNon))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel9).add(examOui)
										.add(examNon))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(respApOui).add(respApNon)
										.add(jLabel11))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(affHorairesHamacOui)
										.add(affHorairesHamacNon).add(jLabel17))
								.add(18, 18, 18)
								.add(jPanel1Layout
										.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel18)
										.add(jLabel19)
										.add(tIntervalleMinimum, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(btEnregistrer2))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jPanel1Layout
										.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
										.add(cbVisibilite, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jPanel1Layout.createSequentialGroup().add(jLabel12)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jLabel16)))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jPanel1Layout
										.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
										.add(cbTypeResa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel20))
								.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).add(jLabel8).addContainerGap()));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup()
						.addContainerGap()
						.add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().addContainerGap()
						.add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				PreferencesView dialog = new PreferencesView(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	protected javax.swing.JRadioButton affHorairesHamacNon;
	protected javax.swing.JRadioButton affHorairesHamacOui;
	protected javax.swing.JRadioButton anneeCivileNon;
	protected javax.swing.JRadioButton anneeCivileOui;
	protected javax.swing.JButton btEnregistrer;
	protected javax.swing.JButton btEnregistrer2;
	protected javax.swing.ButtonGroup buttonGroup1;
	protected javax.swing.ButtonGroup buttonGroup10;
	protected javax.swing.ButtonGroup buttonGroup11;
	protected javax.swing.ButtonGroup buttonGroup2;
	protected javax.swing.ButtonGroup buttonGroup3;
	protected javax.swing.ButtonGroup buttonGroup4;
	protected javax.swing.ButtonGroup buttonGroup5;
	protected javax.swing.ButtonGroup buttonGroup6;
	protected javax.swing.ButtonGroup buttonGroup7;
	protected javax.swing.ButtonGroup buttonGroup8;
	protected javax.swing.ButtonGroup buttonGroup9;
	protected javax.swing.JComboBox cbTypeResa;
	protected javax.swing.JComboBox cbVisibilite;
	protected javax.swing.JRadioButton colorECNon;
	protected javax.swing.JRadioButton colorECOui;
	protected javax.swing.JRadioButton comEnsNon;
	protected javax.swing.JRadioButton comEnsOui;
	protected javax.swing.JRadioButton examNon;
	protected javax.swing.JRadioButton examOui;
	protected javax.swing.JLabel jLabel1;
	protected javax.swing.JLabel jLabel10;
	protected javax.swing.JLabel jLabel11;
	protected javax.swing.JLabel jLabel12;
	protected javax.swing.JLabel jLabel13;
	protected javax.swing.JLabel jLabel14;
	protected javax.swing.JLabel jLabel15;
	protected javax.swing.JLabel jLabel16;
	protected javax.swing.JLabel jLabel17;
	protected javax.swing.JLabel jLabel18;
	protected javax.swing.JLabel jLabel19;
	protected javax.swing.JLabel jLabel20;
	protected javax.swing.JLabel jLabel3;
	protected javax.swing.JLabel jLabel4;
	protected javax.swing.JLabel jLabel5;
	protected javax.swing.JLabel jLabel6;
	protected javax.swing.JLabel jLabel7;
	protected javax.swing.JLabel jLabel8;
	protected javax.swing.JLabel jLabel9;
	protected javax.swing.JPanel jPanel1;
	protected javax.swing.JLabel labelSendMailOccupants;
	protected javax.swing.JRadioButton multSelectionGrpNon;
	protected javax.swing.JRadioButton multSelectionGrpOui;
	protected javax.swing.JRadioButton parcoursComNon;
	protected javax.swing.JRadioButton parcoursComOui;
	protected javax.swing.JRadioButton respApNon;
	protected javax.swing.JRadioButton respApOui;
	protected javax.swing.JRadioButton sendMailDepositairesNon;
	protected javax.swing.JRadioButton sendMailDepositairesOui;
	protected javax.swing.JRadioButton sendMailOccupantsNon;
	protected javax.swing.JRadioButton sendMailOccupantsOui;
	protected javax.swing.JTextField tDebImpress;
	protected javax.swing.JTextField tFinImpress;
	protected javax.swing.JTextField tIntervalleMinimum;
	protected javax.swing.JRadioButton tooltipPlanningNon;
	protected javax.swing.JRadioButton tooltipPlanningOui;

	// End of variables declaration//GEN-END:variables
	public javax.swing.JRadioButton getAnneeCivileNon() {
		return anneeCivileNon;
	}

	public javax.swing.JRadioButton getAnneeCivileOui() {
		return anneeCivileOui;
	}

	public javax.swing.JRadioButton getColorECNon() {
		return colorECNon;
	}

	public javax.swing.JRadioButton getColorECOui() {
		return colorECOui;
	}

	public javax.swing.JRadioButton getComEnsNon() {
		return comEnsNon;
	}

	public javax.swing.JRadioButton getComEnsOui() {
		return comEnsOui;
	}

	public javax.swing.JRadioButton getExamNon() {
		return examNon;
	}

	public javax.swing.JRadioButton getExamOui() {
		return examOui;
	}

	public javax.swing.JRadioButton getMultSelectionGrpNon() {
		return multSelectionGrpNon;
	}

	public javax.swing.JRadioButton getMultSelectionGrpOui() {
		return multSelectionGrpOui;
	}

	public javax.swing.JRadioButton getParcoursComNon() {
		return parcoursComNon;
	}

	public javax.swing.JRadioButton getParcoursComOui() {
		return parcoursComOui;
	}

	public javax.swing.JRadioButton getRespApNon() {
		return respApNon;
	}

	public javax.swing.JRadioButton getRespApOui() {
		return respApOui;
	}

	public javax.swing.JRadioButton getSendMailDepositairesNon() {
		return sendMailDepositairesNon;
	}

	public javax.swing.JRadioButton getSendMailDepositairesOui() {
		return sendMailDepositairesOui;
	}

	public javax.swing.JRadioButton getSendMailOccupantsNon() {
		return sendMailOccupantsNon;
	}

	public javax.swing.JRadioButton getSendMailOccupantsOui() {
		return sendMailOccupantsOui;
	}

	public javax.swing.JTextField gettDebImpress() {
		return tDebImpress;
	}

	public javax.swing.JTextField gettFinImpress() {
		return tFinImpress;
	}

	public javax.swing.JRadioButton getTooltipPlanningNon() {
		return tooltipPlanningNon;
	}

	public javax.swing.JRadioButton getTooltipPlanningOui() {
		return tooltipPlanningOui;
	}

	public javax.swing.JButton getBtEnregistrer() {
		return btEnregistrer;
	}

	public javax.swing.JComboBox getCbVisibilite() {
		return cbVisibilite;
	}

	public javax.swing.JLabel getLabelSendMailOccupants() {
		return labelSendMailOccupants;
	}

	public javax.swing.JRadioButton getAffHorairesHamacNon() {
		return affHorairesHamacNon;
	}

	public javax.swing.JRadioButton getAffHorairesHamacOui() {
		return affHorairesHamacOui;
	}

	public javax.swing.JButton getBtEnregistrer2() {
		return btEnregistrer2;
	}

	public javax.swing.JTextField gettIntervalleMinimum() {
		return tIntervalleMinimum;
	}

	public javax.swing.JComboBox getCbTypeResa() {
		return cbTypeResa;
	}

}
