/*
 * Copyright COCKTAIL (www.cocktail.org), 1995, 2011 This software
 * is governed by the CeCILL license under French law and abiding by the
 * rules of distribution of free software. You can use, modify and/or
 * redistribute the software under the terms of the CeCILL license as
 * circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability. In this
 * respect, the user's attention is drawn to the risks associated with loading,
 * using, modifying and/or developing or reproducing the software by the user
 * in light of its specific status of free software, that may mean that it
 * is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security. The
 * fact that you are presently reading this means that you have had knowledge
 * of the CeCILL license and that you accept its terms.
 */
package edtscol.client.composant;

import javax.swing.JDialog;

import org.cocktail.superplan.client.metier.ResaObjet;
import org.cocktail.superplan.client.metier.Salles;

import com.webobjects.eocontrol.EOEditingContext;
import com.webobjects.foundation.NSArray;

import edtscol.client.recherche.SalleLibreController;
import fr.univlr.common.utilities.WindowHandler;

public class CreationObjetCtrl extends javax.swing.JDialog {

	private String label;
	private Salles salle;
	private boolean reservable;

	private EOEditingContext eContext;

	public CreationObjetCtrl(JDialog owner, String title, EOEditingContext context, ResaObjet objet) {
		super(owner, title, true);
		eContext = context;
		initComponents();
		tLabelSalle.setEditable(false);
		setTitle(title);
		if (objet != null) {
			label = objet.roLibelle2();
			tLabel.setText(label);
			reservable = (objet.roReservable() != null && objet.roReservable().equals("O"));
			cbReservable.setSelected(reservable);
			salle = objet.salle();
			if (salle != null) {
				tLabelSalle.setText(salle.detailSalle());
			}
		}
		setLocation(owner.getX() + 20, owner.getY() + 20);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
	 * method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		tLabel = new javax.swing.JTextField();
		bValider = new javax.swing.JButton();
		bAnnuler = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		bChoisirSalle = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		tLabelSalle = new javax.swing.JTextArea();
		cbReservable = new javax.swing.JCheckBox();
		bRetirerSalle = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("Libellé :");

		bValider.setText("Valider");
		bValider.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bValiderActionPerformed(evt);
			}
		});

		bAnnuler.setText("Annuler");
		bAnnuler.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bAnnulerActionPerformed(evt);
			}
		});

		jLabel2.setText("Salle où est localisé l'objet :");

		bChoisirSalle.setText("Choisir une salle");
		bChoisirSalle.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bChoisirSalleActionPerformed(evt);
			}
		});

		tLabelSalle.setColumns(20);
		tLabelSalle.setEditable(false);
		tLabelSalle.setRows(5);
		jScrollPane1.setViewportView(tLabelSalle);

		cbReservable.setText("Réservable");
		cbReservable.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cbReservableActionPerformed(evt);
			}
		});

		bRetirerSalle.setText("Retirer la salle");
		bRetirerSalle.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bRetirerSalleActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup()
						.addContainerGap()
						.add(layout
								.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(layout
										.createSequentialGroup()
										.add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 69,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(tLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
								.add(layout
										.createSequentialGroup()
										.add(305, 305, 305)
										.add(bAnnuler, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(bValider, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
								.add(layout
										.createSequentialGroup()
										.add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(layout
												.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
												.add(bChoisirSalle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(bRetirerSalle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
								.add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 346, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(cbReservable)).addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.addContainerGap()
						.add(layout
								.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jLabel1)
								.add(tLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
						.add(cbReservable)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 18, Short.MAX_VALUE)
						.add(jLabel2)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(layout
								.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(layout.createSequentialGroup().add(bChoisirSalle).add(7, 7, 7).add(bRetirerSalle))
								.add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.add(18, 18, 18).add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING).add(bAnnuler).add(bValider))
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void bRetirerSalleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bRetirerSalleActionPerformed
		salle = null;
		tLabelSalle.setText(null);
	}// GEN-LAST:event_bRetirerSalleActionPerformed

	private void cbReservableActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbReservableActionPerformed
		reservable = cbReservable.isSelected();
	}// GEN-LAST:event_cbReservableActionPerformed

	private void bValiderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bValiderActionPerformed
		setLabel(tLabel.getText());
		setVisible(false);// GEN-LAST:event_bValiderActionPerformed
	}

	private void bAnnulerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bAnnulerActionPerformed
		label = null;
		setVisible(false);
	}// GEN-LAST:event_bAnnulerActionPerformed

	private void bChoisirSalleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bChoisirSalleActionPerformed
		SalleLibreController ctrl = new SalleLibreController(eContext);
		ctrl.setModeDepositaire(true);
		WindowHandler.runModal(ctrl, "Recherche étendue de salle");
		NSArray<Salles> sallesSelectionnees = ctrl.getSallesSelectionnees();

		if (sallesSelectionnees.count() == 0) {
			salle = null;
			return;
		}
		else {
			salle = sallesSelectionnees.objectAtIndex(0);
			tLabelSalle.setText(salle.detailSalle());
		}
	}// GEN-LAST:event_bChoisirSalleActionPerformed

	public String getLabel() {
		return label;
	}

	public void setLabel(String aLabel) {
		label = aLabel;
	}

	public Salles getSalle() {
		return salle;
	}

	public void setSalle(Salles salle) {
		this.salle = salle;
	}

	public boolean isReservable() {
		return reservable;
	}

	public void setReservable(boolean reservable) {
		this.reservable = reservable;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton bAnnuler;
	private javax.swing.JButton bChoisirSalle;
	private javax.swing.JButton bRetirerSalle;
	private javax.swing.JButton bValider;
	private javax.swing.JCheckBox cbReservable;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField tLabel;
	private javax.swing.JTextArea tLabelSalle;
	// End of variables declaration//GEN-END:variables

}
