/*
 * Copyright COCKTAIL (www.cocktail.org), 1995, 2011 This software
 * is governed by the CeCILL license under French law and abiding by the
 * rules of distribution of free software. You can use, modify and/or
 * redistribute the software under the terms of the CeCILL license as
 * circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability. In this
 * respect, the user's attention is drawn to the risks associated with loading,
 * using, modifying and/or developing or reproducing the software by the user
 * in light of its specific status of free software, that may mean that it
 * is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security. The
 * fact that you are presently reading this means that you have had knowledge
 * of the CeCILL license and that you accept its terms.
 */
package edtscol.client.gestionreservation;

/**
 * 
 * @author pdemeyer
 */
public class InspecteurView extends javax.swing.JDialog {

	/** Creates new form InspecteurView */
	public InspecteurView(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		initGui();
	}

	public void initGui() {
		// this.setAlwaysOnTop(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
	 * method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		matAff = new javax.swing.ButtonGroup();
		matTypeResa = new javax.swing.ButtonGroup();
		dayListPanel = new javax.swing.JPanel();
		comboAnnees = new javax.swing.JComboBox();
		tNumero = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		taCommentaire = new javax.swing.JTextPane();
		ckDt = new javax.swing.JCheckBox();
		vuePanier = new javax.swing.JPanel();
		bNouveau = new javax.swing.JButton();
		bEnregistrer = new javax.swing.JButton();
		bModifier = new javax.swing.JButton();
		bDuppliquer = new javax.swing.JButton();
		bSupprimer = new javax.swing.JButton();
		jPanel465 = new javax.swing.JPanel();
		labelHrDebut = new javax.swing.JLabel();
		labelHrFin = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		tHrDeb = new javax.swing.JTextField();
		tMinDeb = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		tHrFin = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		tMinFin = new javax.swing.JTextField();
		tSemaines = new javax.swing.JTextField();
		cbExpert = new javax.swing.JCheckBox();
		labelDuree = new javax.swing.JLabel();
		tHrDuree = new javax.swing.JTextField();
		labelDuree2 = new javax.swing.JLabel();
		tMinDuree = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jRadioButton2 = new javax.swing.JRadioButton();
		jRadioButton3 = new javax.swing.JRadioButton();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton4 = new javax.swing.JRadioButton();
		jRadioButton5 = new javax.swing.JRadioButton();
		jRadioButton6 = new javax.swing.JRadioButton();
		jRadioButton7 = new javax.swing.JRadioButton();
		jRadioButton8 = new javax.swing.JRadioButton();
		btHistorique = new javax.swing.JButton();

		setTitle("Inspecteur");
		setResizable(false);

		dayListPanel.setPreferredSize(new java.awt.Dimension(260, 22));
		dayListPanel.setLayout(new java.awt.BorderLayout());

		comboAnnees.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		tNumero.setEditable(false);
		tNumero.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
		tNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		tNumero.setText("info");

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10));
		jLabel6.setText("Motif de la réservation");

		jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
		jScrollPane1.setViewportView(taCommentaire);

		ckDt.setText("DT");

		vuePanier.setPreferredSize(new java.awt.Dimension(420, 491));
		vuePanier.setLayout(new java.awt.BorderLayout());

		bNouveau.setMaximumSize(new java.awt.Dimension(30, 30));
		bNouveau.setMinimumSize(new java.awt.Dimension(30, 30));
		bNouveau.setPreferredSize(new java.awt.Dimension(30, 30));

		bEnregistrer.setMaximumSize(new java.awt.Dimension(30, 30));
		bEnregistrer.setMinimumSize(new java.awt.Dimension(30, 30));
		bEnregistrer.setPreferredSize(new java.awt.Dimension(30, 30));

		bModifier.setMaximumSize(new java.awt.Dimension(30, 30));
		bModifier.setMinimumSize(new java.awt.Dimension(30, 30));
		bModifier.setPreferredSize(new java.awt.Dimension(30, 30));

		bDuppliquer.setMaximumSize(new java.awt.Dimension(30, 30));
		bDuppliquer.setMinimumSize(new java.awt.Dimension(30, 30));
		bDuppliquer.setPreferredSize(new java.awt.Dimension(30, 30));

		bSupprimer.setMaximumSize(new java.awt.Dimension(30, 30));
		bSupprimer.setMinimumSize(new java.awt.Dimension(30, 30));
		bSupprimer.setPreferredSize(new java.awt.Dimension(30, 30));

		jPanel465.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		jPanel465.setPreferredSize(new java.awt.Dimension(260, 60));

		labelHrDebut.setFont(new java.awt.Font("Tahoma", 0, 10));
		labelHrDebut.setText("Heures de");

		labelHrFin.setFont(new java.awt.Font("Tahoma", 0, 10));
		labelHrFin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		labelHrFin.setText("à");

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10));
		jLabel3.setText("Semaines");

		tHrDeb.setFont(new java.awt.Font("Tahoma", 0, 10));
		tHrDeb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		tHrDeb.setText("hh");
		tHrDeb.setMaximumSize(new java.awt.Dimension(26, 19));
		tHrDeb.setMinimumSize(new java.awt.Dimension(26, 19));
		tHrDeb.setPreferredSize(new java.awt.Dimension(26, 19));

		tMinDeb.setFont(new java.awt.Font("Tahoma", 0, 10));
		tMinDeb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		tMinDeb.setText("mm");
		tMinDeb.setMaximumSize(new java.awt.Dimension(26, 19));
		tMinDeb.setMinimumSize(new java.awt.Dimension(26, 19));
		tMinDeb.setPreferredSize(new java.awt.Dimension(26, 19));

		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10));
		jLabel4.setText(":");

		tHrFin.setFont(new java.awt.Font("Tahoma", 0, 10));
		tHrFin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		tHrFin.setText("hh");
		tHrFin.setMaximumSize(new java.awt.Dimension(26, 19));
		tHrFin.setMinimumSize(new java.awt.Dimension(26, 19));
		tHrFin.setPreferredSize(new java.awt.Dimension(26, 19));

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10));
		jLabel5.setText(":");

		tMinFin.setFont(new java.awt.Font("Tahoma", 0, 10));
		tMinFin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		tMinFin.setText("mm");
		tMinFin.setMaximumSize(new java.awt.Dimension(26, 19));
		tMinFin.setMinimumSize(new java.awt.Dimension(26, 19));
		tMinFin.setPreferredSize(new java.awt.Dimension(26, 19));

		tSemaines.setFont(new java.awt.Font("Tahoma", 0, 10));

		cbExpert.setText("Expert");
		cbExpert.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		cbExpert.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

		labelDuree.setFont(new java.awt.Font("Tahoma", 0, 10));
		labelDuree.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		labelDuree.setText("Durée");
		labelDuree.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

		tHrDuree.setFont(new java.awt.Font("Tahoma", 0, 10));
		tHrDuree.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		tHrDuree.setText("hh");
		tHrDuree.setMaximumSize(new java.awt.Dimension(26, 19));
		tHrDuree.setMinimumSize(new java.awt.Dimension(26, 19));
		tHrDuree.setPreferredSize(new java.awt.Dimension(26, 19));

		labelDuree2.setFont(new java.awt.Font("Tahoma", 0, 10));
		labelDuree2.setText(":");

		tMinDuree.setFont(new java.awt.Font("Tahoma", 0, 10));
		tMinDuree.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		tMinDuree.setText("mm");
		tMinDuree.setMaximumSize(new java.awt.Dimension(26, 19));
		tMinDuree.setMinimumSize(new java.awt.Dimension(26, 19));
		tMinDuree.setPreferredSize(new java.awt.Dimension(26, 19));

		org.jdesktop.layout.GroupLayout jPanel465Layout = new org.jdesktop.layout.GroupLayout(jPanel465);
		jPanel465.setLayout(jPanel465Layout);
		jPanel465Layout.setHorizontalGroup(jPanel465Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel465Layout
						.createSequentialGroup()
						.addContainerGap()
						.add(jPanel465Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(labelHrDebut, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
								.add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jPanel465Layout
								.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
								.add(jPanel465Layout
										.createSequentialGroup()
										.add(tHrDeb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jLabel4)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(tMinDeb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(labelHrFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(tHrFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jLabel5)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(tMinFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).add(tSemaines))
						.add(jPanel465Layout
								.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(jPanel465Layout
										.createSequentialGroup()
										.add(44, 44, 44)
										.add(cbExpert, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 72,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(jPanel465Layout
										.createSequentialGroup()
										.add(8, 8, 8)
										.add(labelDuree, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(tHrDuree, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(labelDuree2)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
										.add(tMinDuree, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))).addContainerGap()));
		jPanel465Layout.setVerticalGroup(jPanel465Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				org.jdesktop.layout.GroupLayout.TRAILING,
				jPanel465Layout
						.createSequentialGroup()
						.add(jPanel465Layout
								.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(tHrDeb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jLabel4)
								.add(tMinDeb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(labelHrFin)
								.add(labelHrDebut)
								.add(tHrFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jLabel5)
								.add(tMinFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(tHrDuree, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(labelDuree2)
								.add(tMinDuree, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(labelDuree))
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
						.add(jPanel465Layout
								.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jLabel3)
								.add(tSemaines, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(cbExpert))
						.addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		matAff.add(jRadioButton2);
		jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 12));
		jRadioButton2.setText("Public");

		matAff.add(jRadioButton3);
		jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 12));
		jRadioButton3.setText("Privé");

		matAff.add(jRadioButton1);
		jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 12));
		jRadioButton1.setSelected(true);
		jRadioButton1.setText("Service");

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel2Layout
						.createSequentialGroup()
						.addContainerGap()
						.add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(jRadioButton1).add(jRadioButton2)
								.add(jRadioButton3)).addContainerGap(12, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel2Layout.createSequentialGroup().addContainerGap()
						.add(jRadioButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
						.add(jRadioButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
						.add(jRadioButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(6, Short.MAX_VALUE)));

		matTypeResa.add(jRadioButton4);
		jRadioButton4.setText("Enseignement");

		matTypeResa.add(jRadioButton5);
		jRadioButton5.setText("Réunion");

		matTypeResa.add(jRadioButton6);
		jRadioButton6.setText("Examen");

		matTypeResa.add(jRadioButton7);
		jRadioButton7.setText("Blocage");

		matTypeResa.add(jRadioButton8);
		jRadioButton8.setText("Etudiants");

		btHistorique.setMaximumSize(new java.awt.Dimension(30, 30));
		btHistorique.setMinimumSize(new java.awt.Dimension(30, 30));
		btHistorique.setPreferredSize(new java.awt.Dimension(30, 30));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup()
						.add(layout
								.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(layout
										.createSequentialGroup()
										.add(10, 10, 10)
										.add(dayListPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 287,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(layout.createSequentialGroup().add(10, 10, 10).add(jRadioButton4)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jRadioButton5)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jRadioButton6)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jRadioButton7)
										.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(jRadioButton8))
								.add(layout
										.createSequentialGroup()
										.addContainerGap()
										.add(layout
												.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
												.add(comboAnnees, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(layout
														.createSequentialGroup()
														.add(jPanel465, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 369,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(10, 10, 10)
														.add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
								.add(org.jdesktop.layout.GroupLayout.TRAILING,
										layout.createSequentialGroup()
												.addContainerGap()
												.add(layout
														.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
														.add(org.jdesktop.layout.GroupLayout.LEADING, tNumero,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
														.add(org.jdesktop.layout.GroupLayout.LEADING, jLabel6,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
														.add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
														.add(org.jdesktop.layout.GroupLayout.LEADING, vuePanier,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(layout
														.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
														.add(btHistorique, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(bNouveau, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(bEnregistrer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(bModifier, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(bDuppliquer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(bSupprimer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(ckDt)))).addContainerGap()));

		layout.linkSize(new java.awt.Component[] { jRadioButton4, jRadioButton5, jRadioButton6, jRadioButton7, jRadioButton8 },
				org.jdesktop.layout.GroupLayout.HORIZONTAL);

		layout.linkSize(new java.awt.Component[] { jScrollPane1, vuePanier }, org.jdesktop.layout.GroupLayout.HORIZONTAL);

		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.addContainerGap()
						.add(layout
								.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(dayListPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(comboAnnees, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(jPanel2, 0, 64, Short.MAX_VALUE)
								.add(jPanel465, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(layout
								.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jRadioButton5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jRadioButton6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jRadioButton7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jRadioButton8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jRadioButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(layout
								.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
								.add(tNumero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(btHistorique, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
						.add(layout
								.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
								.add(org.jdesktop.layout.GroupLayout.TRAILING,
										layout.createSequentialGroup()
												.add(jLabel6)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(layout
														.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
														.add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(ckDt))
												.add(168, 168, 168)
												.add(bNouveau, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(bEnregistrer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(bModifier, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(bDuppliquer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
												.add(bSupprimer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(175, 175, 175))
								.add(layout.createSequentialGroup().add(97, 97, 97)
										.add(vuePanier, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE).add(11, 11, 11)))));

		layout.linkSize(new java.awt.Component[] { jPanel2, jPanel465 }, org.jdesktop.layout.GroupLayout.VERTICAL);

		layout.linkSize(new java.awt.Component[] { jRadioButton4, jRadioButton5, jRadioButton6, jRadioButton7, jRadioButton8 },
				org.jdesktop.layout.GroupLayout.VERTICAL);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				InspecteurView dialog = new InspecteurView(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	protected javax.swing.JButton bDuppliquer;
	protected javax.swing.JButton bEnregistrer;
	protected javax.swing.JButton bModifier;
	protected javax.swing.JButton bNouveau;
	protected javax.swing.JButton bSupprimer;
	protected javax.swing.JButton btHistorique;
	protected javax.swing.JCheckBox cbExpert;
	protected javax.swing.JCheckBox ckDt;
	protected javax.swing.JComboBox comboAnnees;
	protected javax.swing.JPanel dayListPanel;
	protected javax.swing.JLabel jLabel3;
	protected javax.swing.JLabel jLabel4;
	protected javax.swing.JLabel jLabel5;
	protected javax.swing.JLabel jLabel6;
	protected javax.swing.JPanel jPanel2;
	protected javax.swing.JPanel jPanel465;
	protected javax.swing.JRadioButton jRadioButton1;
	protected javax.swing.JRadioButton jRadioButton2;
	protected javax.swing.JRadioButton jRadioButton3;
	protected javax.swing.JRadioButton jRadioButton4;
	protected javax.swing.JRadioButton jRadioButton5;
	protected javax.swing.JRadioButton jRadioButton6;
	protected javax.swing.JRadioButton jRadioButton7;
	protected javax.swing.JRadioButton jRadioButton8;
	protected javax.swing.JScrollPane jScrollPane1;
	protected javax.swing.JLabel labelDuree;
	protected javax.swing.JLabel labelDuree2;
	protected javax.swing.JLabel labelHrDebut;
	protected javax.swing.JLabel labelHrFin;
	protected javax.swing.ButtonGroup matAff;
	protected javax.swing.ButtonGroup matTypeResa;
	protected javax.swing.JTextField tHrDeb;
	protected javax.swing.JTextField tHrDuree;
	protected javax.swing.JTextField tHrFin;
	protected javax.swing.JTextField tMinDeb;
	protected javax.swing.JTextField tMinDuree;
	protected javax.swing.JTextField tMinFin;
	protected javax.swing.JTextField tNumero;
	protected javax.swing.JTextField tSemaines;
	protected javax.swing.JTextPane taCommentaire;
	protected javax.swing.JPanel vuePanier;

	// End of variables declaration//GEN-END:variables
	public javax.swing.JPanel getDayListPanel() {
		return dayListPanel;
	}

	public javax.swing.JPanel getVuePanier() {
		return vuePanier;
	}

	public javax.swing.JButton getBDuppliquer() {
		return bDuppliquer;
	}

	public javax.swing.JButton getBEnregistrer() {
		return bEnregistrer;
	}

	public javax.swing.JButton getBModifier() {
		return bModifier;
	}

	public javax.swing.JButton getBNouveau() {
		return bNouveau;
	}

	public javax.swing.JButton getBSupprimer() {
		return bSupprimer;
	}

	public javax.swing.JTextField getTHrDeb() {
		return tHrDeb;
	}

	public javax.swing.JTextField getTHrFin() {
		return tHrFin;
	}

	public javax.swing.JTextField getTMinDeb() {
		return tMinDeb;
	}

	public javax.swing.JTextField getTMinFin() {
		return tMinFin;
	}

	public javax.swing.JTextField getTNumero() {
		return tNumero;
	}

	public javax.swing.JTextField getTSemaines() {
		return tSemaines;
	}

	public javax.swing.JTextPane getTaCommentaire() {
		return taCommentaire;
	}

	public javax.swing.JComboBox getComboAnnees() {
		return comboAnnees;
	}

	public javax.swing.JCheckBox getCkDt() {
		return ckDt;
	}

	public javax.swing.ButtonGroup getMatAff() {
		return matAff;
	}

	public javax.swing.ButtonGroup getMatTypeResa() {
		return matTypeResa;
	}

	public javax.swing.JCheckBox getCbExpert() {
		return cbExpert;
	}

	public javax.swing.JLabel getLabelDuree() {
		return labelDuree;
	}

	public javax.swing.JLabel getLabelDuree2() {
		return labelDuree2;
	}

	public javax.swing.JTextField getTHrDuree() {
		return tHrDuree;
	}

	public javax.swing.JTextField getTMinDuree() {
		return tMinDuree;
	}

	public javax.swing.JLabel getLabelHrDebut() {
		return labelHrDebut;
	}

	public javax.swing.JLabel getLabelHrFin() {
		return labelHrFin;
	}

	public javax.swing.JButton getBtHistorique() {
		return btHistorique;
	}

}
