-- edtscol
-- update de la version EdtScol (version appli 1.2.3) vers la version SuperPlan (version base 1.1.0)

--
CREATE TABLE edtscol.CATEG_OBJET ( 
  COB_ORDRE    NUMBER        NOT NULL, 
  COB_LIBELLE  VARCHAR2 (200)  NOT NULL );

CREATE UNIQUE INDEX edtscol.PRIM_COB ON 
  edtscol.CATEG_OBJET(COB_ORDRE); 

INSERT INTO edtscol.CATEG_OBJET ( COB_ORDRE, COB_LIBELLE ) VALUES ( 
1, 'MATERIEL INFORMATIQUE'); 
INSERT INTO edtscol.CATEG_OBJET ( COB_ORDRE, COB_LIBELLE ) VALUES ( 
2, 'FOURNITURES DE BUREAU'); 
INSERT INTO edtscol.CATEG_OBJET ( COB_ORDRE, COB_LIBELLE ) VALUES ( 
3, 'MATERIEL AUDIOVISUEL '); 
INSERT INTO edtscol.CATEG_OBJET ( COB_ORDRE, COB_LIBELLE ) VALUES ( 
4, 'MATERIEL BUREAUTIQUE'); 
INSERT INTO edtscol.CATEG_OBJET ( COB_ORDRE, COB_LIBELLE ) VALUES ( 
5, 'MATERIEL DE LABORATOIRE'); 
INSERT INTO edtscol.CATEG_OBJET ( COB_ORDRE, COB_LIBELLE ) VALUES ( 
6, 'MATERIEL DE TRANSPORT'); 
INSERT INTO edtscol.CATEG_OBJET ( COB_ORDRE, COB_LIBELLE ) VALUES ( 
7, 'MOBILIERS'); 
INSERT INTO edtscol.CATEG_OBJET ( COB_ORDRE, COB_LIBELLE ) VALUES ( 
8, 'MATERIEL DIVERS'); 
INSERT INTO edtscol.CATEG_OBJET ( COB_ORDRE, COB_LIBELLE ) VALUES ( 
9, 'OUTILLAGES'); 
INSERT INTO edtscol.CATEG_OBJET ( COB_ORDRE, COB_LIBELLE ) VALUES ( 
11, 'IMMOBILIER'); 
INSERT INTO edtscol.CATEG_OBJET ( COB_ORDRE, COB_LIBELLE ) VALUES ( 
12, 'SUAPSE'); 
INSERT INTO edtscol.CATEG_OBJET ( COB_ORDRE, COB_LIBELLE ) VALUES ( 
13, 'VEHICULES');

--
CREATE TABLE edtscol.TYPE_OBJET ( 
  TOB_ORDRE    NUMBER        NOT NULL, 
  TOB_LIBELLE  VARCHAR2 (200)  NOT NULL, 
  COB_ORDRE    NUMBER        NOT NULL ) ; 

CREATE INDEX edtscol.TYPE_OBJET_COB_ORDRE ON 
  edtscol.TYPE_OBJET(COB_ORDRE) 
; 

INSERT INTO edtscol.TYPE_OBJET VALUES (1, 'APPAREILS CCA', 5);
INSERT INTO edtscol.TYPE_OBJET VALUES (2, 'CHAMBRES', 11);
INSERT INTO edtscol.TYPE_OBJET VALUES (3, 'DEPARTEMENT GENIE CIVIL', 4);
INSERT INTO edtscol.TYPE_OBJET VALUES (4, 'DEPARTEMENT MATHEMATIQUES', 4);
INSERT INTO edtscol.TYPE_OBJET VALUES (5, 'GENERATEUR DIAPOS', 3);
INSERT INTO edtscol.TYPE_OBJET VALUES (6, 'LECTEUR OPTIQUE', 4);
INSERT INTO edtscol.TYPE_OBJET VALUES (7, 'MATERIEL GEOPHYSIQUE', 5);
INSERT INTO edtscol.TYPE_OBJET VALUES (8, 'MATERIEL GRAVURE', 1);
INSERT INTO edtscol.TYPE_OBJET VALUES (9, 'MATERIEL RESEAU CRI', 1);
INSERT INTO edtscol.TYPE_OBJET VALUES (10, 'MATERIEL VIDEO', 3);
INSERT INTO edtscol.TYPE_OBJET VALUES (11, 'OUTILLAGE CRI', 9);
INSERT INTO edtscol.TYPE_OBJET VALUES (12, 'PORTABLE', 1);
INSERT INTO edtscol.TYPE_OBJET VALUES (13, 'PORTABLE BU', 1);
INSERT INTO edtscol.TYPE_OBJET VALUES (14, 'PORTABLE GI', 1);
INSERT INTO edtscol.TYPE_OBJET VALUES (15, 'SUAPSE CLASS8 Mardi', 12);
INSERT INTO edtscol.TYPE_OBJET VALUES (16, 'SUAPSE CLASS8 Vendredi', 12);
INSERT INTO edtscol.TYPE_OBJET VALUES (17, 'SUAPSE CLASS8 Week-end', 12);
INSERT INTO edtscol.TYPE_OBJET VALUES (18, 'SUAPSE CROISIERE', 12);
INSERT INTO edtscol.TYPE_OBJET VALUES (19, 'SUAPSE F 1', 12);
INSERT INTO edtscol.TYPE_OBJET VALUES (20, 'SUAPSE HC 15', 12);
INSERT INTO edtscol.TYPE_OBJET VALUES (21, 'SUAPSE HC 16', 12);
INSERT INTO edtscol.TYPE_OBJET VALUES (22, 'SUAPSE P.A.V.', 12);
INSERT INTO edtscol.TYPE_OBJET VALUES (23, 'SUAPSE 420', 12);
INSERT INTO edtscol.TYPE_OBJET VALUES (24, 'SUPPRIMER', 1);
INSERT INTO edtscol.TYPE_OBJET VALUES (25, 'TABLETTE VIDEO', 3);
INSERT INTO edtscol.TYPE_OBJET VALUES (26, 'VEHICULES', 13);
INSERT INTO edtscol.TYPE_OBJET VALUES (27, 'VIDEO PROJECTEUR', 3);

CREATE UNIQUE INDEX edtscol.PRIM_TOB ON 
  edtscol.TYPE_OBJET(TOB_ORDRE);

-- 
CREATE OR REPLACE VIEW edtscol.V_TREE_OBJETS ( C_STRUCTURE, 
C_STRUCTURE_PERE, LL_STRUCTURE, PERS_ID ) AS SELECT TO_CHAR(cob_ordre),'0',cob_libelle,1 FROM edtscol.CATEG_OBJET
UNION
SELECT TO_CHAR(tob_ordre),TO_CHAR(t1.cob_ordre),t2.tob_libelle,0 FROM edtscol.CATEG_OBJET t1, edtscol.TYPE_OBJET t2
WHERE t1.cob_ordre=t2.cob_ordre;

--
CREATE OR REPLACE VIEW GRHUM.V_TREE_SALLES ( C_STRUCTURE, 
C_STRUCTURE_PERE, LL_STRUCTURE, PERS_ID ) AS SELECT DISTINCT LOCAL.c_Local ,'0',appellation,1 FROM 
GRHUM.LOCAL,GRHUM.SALLES WHERE LOCAL.c_local=SALLES.c_local AND SALLES.sal_reservable='O'
UNION
SELECT DISTINCT SUBSTR(t2.tsal_libelle,1,20) || c_local,c_local,tsal_libelle,0
FROM GRHUM.SALLES t1,TYPE_SALLE t2 WHERE t1.tsal_numero=t2.tsal_numero AND t1.sal_reservable='O';

--
CREATE OR REPLACE VIEW GRHUM.V_GROUPE_PERSONNE ( LL_STRUCTURE, 
C_STRUCTURE, C_STRUCTURE_PERE, PERS_ID ) AS SELECT
LL_STRUCTURE,C_STRUCTURE,C_STRUCTURE_PERE,PERS_ID FROM grhum.STRUCTURE_ULR WHERE LL_STRUCTURE NOT LIKE '$%'
UNION
SELECT pers_nomptr || ' ' || pers_lc,'P' || TO_CHAR(PERSONNE.pers_id),t1.c_structure,PERSONNE.PERS_ID
FROM grhum.PERSONNE,grhum.REPART_STRUCTURE,grhum.STRUCTURE_ULR T1,grhum.STRUCTURE_ULR T2
WHERE PERSONNE.pers_id=REPART_STRUCTURE.pers_id
AND REPART_STRUCTURE.C_STRUCTURE=t1.C_STRUCTURE
AND t1.c_structure=t2.c_structure_pere(+)
AND t2.C_STRUCTURE IS NULL AND pers_nomptr IS NOT NULL AND T1.ll_structure NOT LIKE '$%'
UNION
SELECT t1.ll_structure,t1.c_structure,t2.c_structure,t1.PERS_ID
FROM grhum.REPART_STRUCTURE t2,grhum.STRUCTURE_ULR T1
WHERE t1.pers_id=t2.pers_id AND T1.ll_structure NOT LIKE '$%';

--
-- pref_user
ALTER TABLE edtscol.PREF_USER ADD annee_civile NUMBER;
ALTER TABLE edtscol.PREF_USER ADD default_planning NUMBER;

--
CREATE SEQUENCE edtscol.type_objet_seq START WITH 28 NOCACHE;
CREATE SEQUENCE edtscol.categ_objet_seq START WITH 14 NOCACHE;

--
ALTER TABLE reservation.type_objet_kiosque ADD temp_preparer NUMBER;
ALTER TABLE reservation.type_objet_kiosque ADD temp_avant_pret NUMBER;

--
ALTER TABLE reservation.resa_objet_harp ADD rgp_numero VARCHAR2(20);
ALTER TABLE reservation.resa_objet_harp ADD sal_ordre INTEGER;

--
CREATE TABLE reservation.RESA_DEPOSITAIRE_NEW (
  C_STRUCTURE  VARCHAR2(10),
  OBJET_ORDRE  NUMBER
);

--
CREATE TABLE reservation.RESA_OBJET_DEPOS (
  OBJE_ORDRE   NUMBER                           NOT NULL,
  C_STRUCTURE  VARCHAR2(20 BYTE)                NOT NULL
);

--
GRANT SELECT ON jefy_inventaire.LIVRAISON TO reservation;
GRANT SELECT ON jefy_inventaire.LIVRAISON_DETAIL TO reservation;
GRANT SELECT ON jefy_inventaire.INVENTAIRE TO reservation;
GRANT SELECT ON jefy_inventaire.INVENTAIRE_COMPTABLE TO reservation;
GRANT SELECT ON jefy_inventaire.CLE_INVENTAIRE_COMPTABLE TO reservation;

--
CREATE OR REPLACE FORCE VIEW RESERVATION.V_INVENTAIRE_OBJET
(LIV_ORDRE, LID_ORDRE, INV_ID, INVC_ID, CLIC_ID, 
 COMM_ID, ORG_ID, TCD_ORDRE, PCO_NUM, LID_MONTANT, 
 CLIC_NUM_COMPLET, DPCO_ID, LID_LIBELLE, CLIC_COMP, CLIC_CR)
AS 
SELECT l.liv_ordre, ld.lid_ordre,
 i.inv_id, ic.invc_id, cic.clic_id, l.comm_id, ld.org_id, ld.tcd_ordre,
 ld.pco_num, ld.lid_montant, cic.clic_num_complet, ic.dpco_id, ld.LID_LIBELLE, cic.clic_comp,cic.clic_cr
FROM
jefy_inventaire.LIVRAISON l,
jefy_inventaire.LIVRAISON_DETAIL ld,
jefy_inventaire.INVENTAIRE i ,
jefy_inventaire.INVENTAIRE_COMPTABLE ic ,
jefy_inventaire.CLE_INVENTAIRE_COMPTABLE cic
WHERE i.invc_id =  ic.invc_id AND ic.clic_id = cic.clic_id AND ld.lid_ordre = i.lid_ordre AND l.liv_ordre = ld.liv_ordre;

--
CREATE OR REPLACE VIEW edtscol.V_TREE_OBJETS ( C_STRUCTURE,
C_STRUCTURE_PERE, LL_STRUCTURE, PERS_ID ) AS SELECT TO_CHAR(cob_ordre),'0',cob_libelle,1
FROM edtscol.categ_objet
UNION
SELECT LTRIM(TO_CHAR(t1.cob_ordre*1000+tob_ordre,'000009')),TO_CHAR(t1.cob_ordre),t2.tob_libelle,0
FROM edtscol.categ_objet t1,edtscol.type_objet t2
WHERE t1.cob_ordre=t2.cob_ordre;

--
ALTER TABLE RESERVATION.RESA_OBJET_HARP MODIFY (OBJE_LIBELLE1 VARCHAR2(128));

--
CREATE TABLE EDTSCOL.DB_VERSION (
  DB_VERSION  VARCHAR2(10) NOT NULL,
  DB_DATE     DATE,
  DB_COMMENT  VARCHAR2(100) NOT NULL
);

CREATE UNIQUE INDEX EDTSCOL.DB_VERSION_PK ON EDTSCOL.DB_VERSION (DB_VERSION);
ALTER TABLE EDTSCOL.DB_VERSION ADD (CONSTRAINT DB_VERSION_PK PRIMARY KEY (DB_VERSION));
          
-- version...
INSERT INTO EDTSCOL.DB_VERSION VALUES ('1.1.0', TO_DATE('01/11/2007', 'dd/mm/yyyy'), 'Version P5');

--
COMMIT;
